# The URL the site will be built for
base_url = "https://mhfu.vallode.com/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Avoid copying all images to public static directory.
# https://github.com/getzola/zola/issues/1217
# hard_link_static = true

# A list of glob patterns specifying asset files to ignore when the content
# directory is processed. Defaults to none, which means that all asset files are
# copied over to the `public` directory.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*", "**/build_folder"]
ignored_content = ["*-crafting.json"]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

minify_html = true

[search]
include_title = true
include_description = false
include_path = false
include_content = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
weapon_types = [
  "great-sword",
  "long-sword",
  "sword-and-shield",
  "dual-blades",
  "hammer",
  "hunting-horn",
  "lance",
  "gunlance",
  "light-bowgun",
  "heavy-bowgun",
  "bow",
  "decoration"
]

armor_types = [
  "helmet",
  "plate",
  "gauntlets",
  "waist",
  "leggings"
]

monster_types = [
  "lynian",
  "neopteron",
  "herbivore",
  "bird-wyvern",
  "flying-wyvern",
  "piscine-wyvern",
  "carapaceon",
  "pelagus",
  "elder-dragon",
]
