import type { NextConfig } from "next";
import withPWA, { runtimeCaching as defaultRuntimeCaching } from "@ducanh2912/next-pwa";
import fs from "fs";
import path from "path";
import { createHash } from "crypto";

const nextConfig: NextConfig = {
  output: "export",
  trailingSlash: true,
  experimental: { viewTransition: true },
};

// ---------------------------------------------------------------------------
// Offline precache entries (built at config load, i.e. during `next build`).
// Data bundles are read from public/data (generated by scripts/generate-data.ts,
// which runs first in the build script); images are globbed from public/images.
// Each entry's revision is a content hash so updates bust the cache cleanly.
// ---------------------------------------------------------------------------
interface PrecacheEntry {
  url: string;
  revision: string;
}

function hashFile(p: string): string {
  return createHash("md5").update(fs.readFileSync(p)).digest("hex").slice(0, 16);
}

function collectPrecacheEntries(): PrecacheEntry[] {
  const entries: PrecacheEntry[] = [];
  const publicDir = path.join(process.cwd(), "public");

  // All data bundles (+ dictionaries + manifest) from public/data.
  const dataDir = path.join(publicDir, "data");
  if (fs.existsSync(dataDir)) {
    for (const f of fs.readdirSync(dataDir)) {
      if (!f.endsWith(".json")) continue;
      entries.push({ url: `/data/${f}`, revision: hashFile(path.join(dataDir, f)) });
    }
  }

  // Search + calculator payloads (kept for those features).
  for (const extra of ["search-data.json", "weapon-data.json"]) {
    const p = path.join(publicDir, extra);
    if (fs.existsSync(p)) entries.push({ url: `/${extra}`, revision: hashFile(p) });
  }

  // All images (pixel-art sprites / icons).
  const imagesDir = path.join(publicDir, "images");
  const walk = (dir: string) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (/\.(png|jpg|jpeg|webp|gif)$/.test(entry.name)) {
        entries.push({
          url: `/images/${path.relative(imagesDir, full).split(path.sep).join("/")}`,
          revision: hashFile(full),
        });
      }
    }
  };
  if (fs.existsSync(imagesDir)) walk(imagesDir);

  return entries;
}

const additionalManifestEntries = collectPrecacheEntries();
// Version/cacheId from the data manifest hash so data updates invalidate cleanly.
let cacheId = "mhfu-blacksmith";
try {
  const manifest = JSON.parse(
    fs.readFileSync(path.join(process.cwd(), "public", "data", "data-manifest.json"), "utf-8")
  ) as { version?: string };
  if (manifest.version) cacheId = `mhfu-${manifest.version}`;
} catch {
  // manifest not generated yet (e.g. plain `next build` without the pipeline)
}

export default withPWA({
  dest: "public",
  cacheOnFrontEndNav: true,
  aggressiveFrontEndNavCaching: true,
  reloadOnOnline: true,
  disable: process.env.NODE_ENV === "development",
  workboxOptions: {
    disableDevLogs: true,
    cacheId,
    // Precache all data bundles, images, and the app shell at SW install.
    additionalManifestEntries,
    runtimeCaching: [
      {
        // Data bundles: precached by workbox, but also serve the manual
        // offline cache the "Download for offline" button populates.
        urlPattern: /\/data\/.+\.json$/,
        handler: "CacheFirst",
        options: {
          cacheName: "mhfu-offline-v1",
        },
      },
      {
        // Cache data JSON files
        urlPattern: /\/(search-data|weapon-data)\.json$/,
        handler: "CacheFirst",
        options: {
          cacheName: "mhfu-offline-v1",
        },
      },
      {
        // Cache images (pixel art sprites)
        urlPattern: /\/images\/.+\.(png|jpg|webp|gif)$/,
        handler: "CacheFirst",
        options: {
          cacheName: "images",
          expiration: { maxEntries: 1000, maxAgeSeconds: 30 * 24 * 60 * 60 },
        },
      },
      // Every weapon/armor/monster/decoration is its own statically-exported
      // route (~3800 of them) — App Router client navigation needs that
      // specific route's RSC payload (and the "pages" cache for a plain
      // document load/refresh) to exist offline, even though the visible
      // content is rendered from the already-cached compact JSON bundles
      // (src/lib/client-data.ts). We don't proactively download all ~3800
      // pages (see src/lib/offline-cache.ts) — instead, raise next-pwa's
      // default 32-entry cap on these three so pages you've actually
      // browsed (or that were auto-prefetched by <Link>) stay cached instead
      // of getting evicted almost immediately, which previously made
      // offline navigation to anything but the last few visited pages 404.
      {
        urlPattern: ({ request, url: { pathname }, sameOrigin }) =>
          request.headers.get("RSC") === "1" &&
          request.headers.get("Next-Router-Prefetch") === "1" &&
          sameOrigin &&
          !pathname.startsWith("/api/"),
        handler: "NetworkFirst",
        options: {
          cacheName: "pages-rsc-prefetch",
          expiration: { maxEntries: 4000, maxAgeSeconds: 86400 },
        },
      },
      {
        urlPattern: ({ request, url: { pathname }, sameOrigin }) =>
          request.headers.get("RSC") === "1" &&
          sameOrigin &&
          !pathname.startsWith("/api/"),
        handler: "NetworkFirst",
        options: {
          cacheName: "pages-rsc",
          expiration: { maxEntries: 4000, maxAgeSeconds: 86400 },
        },
      },
      {
        urlPattern: ({ url: { pathname }, sameOrigin }) =>
          sameOrigin && !pathname.startsWith("/api/"),
        handler: "NetworkFirst",
        options: {
          cacheName: "pages",
          expiration: { maxEntries: 4000, maxAgeSeconds: 86400 },
        },
      },
      // Supplying a custom `runtimeCaching` array replaces next-pwa's default
      // one entirely (it doesn't merge). Append the defaults after our own
      // rules above (data/image caches, and the higher-capacity page caches)
      // so those take precedence and only truly uncovered request types
      // (cross-origin assets, fonts, etc.) fall through to next-pwa's stock
      // behavior.
      ...defaultRuntimeCaching,
    ],
  },
})(nextConfig);
